---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mypipeline
  name: mypipeline
  namespace: mypipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypipeline
  template:
    metadata:
      labels:
        app: mypipeline
    spec:
      containers:
      - image: accessbankdev.azurecr.io/mypipeline:1818
        name: mypipeline
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: mypipeline
  namespace: mypipeline
spec:
  selector:
    app: mypipeline
  ports:
  - port: 80
    targetPort: 80
